# Generated by Django 3.1.1 on 2021-02-10 04:48

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(validators=[administration.models.phone_validator]),
        ),
    ]
