# Generated by Django 3.1.1 on 2021-02-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0003_auto_20210210_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartcontent',
            unique_together={('cart', 'product')},
        ),
    ]
